- week02/SWEA_16910/SWEA_16910_박진우.java
- week02/SWEA_3131/SWEA_3131_박진우.java
- week02/SWEA_7087/SWEA_7087_박진우.java
> 2주차 문제풀이 박진우

- week02/SWEA_16910/SWEA_16910_원민혁.java
- week02/SWEA_3131/SWEA_3131_원민혁.java
- week02/SWEA_7087/SWEA_7087_원민혁.java
> 2주차 문제풀이 원민혁

- week02/SWEA_16910/SWEA_16910_김명화.java
- week02/SWEA_3131/SWEA_3131_김명화.java
- week02/SWEA_7087/SWEA_7087_김명화.java
> mhk w2 commit

- week03/SWEA_10580/SWEA_10580_박진우.java
- week03/SWEA_4371/SWEA_4371_박진우.java
- week03/SWEA_4613/SWEA_4613_박진우.java
> 3주차 문제풀이 박진우

- week03/SWEA_10580/SWEA_10580_배준영.java
- week03/SWEA_4371/SWEA_4371_배준영.java
- week03/SWEA_4613/SWEA_4613_배준영.java
> Junyeong Bae Week3

- week04/SWEA_3752/SWEA_3752_배준영.java
- week04/SWEA_4615/SWEA_4615_배준영.java
- week04/SWEA_6719/SWEA_6719_배준영.java
> junyeong week04

- week04/SWEA_3752/SWEA_3752_박진우.java
- week04/SWEA_4615/SWEA_4615_박진우.java
- week04/SWEA_6719/SWEA_6719_박진우.java
> 4주차 문제풀이 박진우

- week05/SWEA_1244/SWEA_1244_박진우.java
- week05/SWEA_20019/SWEA_20019_박진우.java
- week05/SWEA_9229/SWEA_9229_박진우.java
5주차 문제를 풀었습니다.
저는 1244번을 단순 구현했는데, 더 쉬운 풀이도 많은 것 같아요
> 5주차 문제풀이 박진우

- week05/SWEA_1244/SWEA_1244_이혜윤.java
- week05/SWEA_20019/SWEA_20019_이혜윤.java
- week05/SWEA_9229/SWEA_9229_이혜윤.java
> 5주차 문제풀이 이혜윤

- week06/SWEA_1865/SWEA_1865_박진우.java
- week06/SWEA_1952/SWEA_1952_박진우.java
- week06/SWEA_5986/SWEA_5986_박진우.java
> 6주차 문제풀이 박진우

- week06/SWEA_1865/SWEA_1865_원민혁.java
- week06/SWEA_1952/SWEA_1952_원민혁.java
- week06/SWEA_5986/SWEA_5986_원민혁.java
> 6주차 APS 원민혁

- week07/BOJ_4963/BOJ_2573_박진우.java
- week07/BOJ_4963/BOJ_4963_박진우.java
7주차 문제를 풀었습니다.
해킹 문제는 시간초과 나서 뺐습니다 😢
> 7주차 문제풀이 박진우

- week08/BOJ_17086/BOJ_17086_원민혁.java
- week08/BOJ_17471/BOJ_17471_원민혁.java
- week08/BOJ_2667/BOJ_2667_원민혁.java
> week08_원민혁

- week08/BOJ_17086/BOJ_17086_김명화.java
- week08/BOJ_17471/BOJ_17471_김명화.java
- week08/BOJ_2667/BOJ_2667_김명화.java
> 8주차 김명화 풀이제출

- week08/BOJ_17086/BOJ_17086_박진우.java
- week08/BOJ_17471/BOJ_17471_박진우.java
- week08/BOJ_2667/BOJ_2667_박진우.java
8주차 문제를 풀었습니다.
[17471](https://www.acmicpc.net/problem/17471) 게리맨더링 문제가 까다로웠어요. 😅
> 8주차 문제풀이 박진우

- week08/BOJ_17086/BOJ_17086_유석민.java
- week08/BOJ_2667/BOJ_2667_유석민.java
> 유석민 8주차 문제풀이

- week09/BOJ_1520/BOJ_1520_김명화.java
- week09/BOJ_15486/BOJ_15486_김명화.java
- week09/BOJ_9465/BOJ_9465_김명화.java
> 9주차 문제풀이 김명화

- week09/BOJ_1520/BOJ_1520_박진우.java
- week09/BOJ_15486/BOJ_15486_박진우.java
- week09/BOJ_9465/BOJ_9465_박진우.java
9주차 문제를 풀었습니다! 😃 
15486_퇴사2는 이전에 유사한 문제를 Top-down으로 풀어서 이번에는 Bottom-up으로 풀어봤습니다.
1520_내리막길은 이전에 [풀었던 문제](https://github.com/Jinops/algorithm/blob/main/baekjoon/1520_%EB%82%B4%EB%A6%AC%EB%A7%89%20%EA%B8%B8.java)였습니다.
> 9주차 문제풀이 박진우

- week09/BOJ_15486/BOJ_15486_유석민.java
- week09/BOJ_9465/BOJ_9465_유석민.java
> 9주차 문제풀이 유석민

- week10/BOJ_16398/BOJ_16398_박진우.java
- week10/BOJ_1916/BOJ_1916_박진우.java
- week10/BOJ_4485/BOJ_4485_박진우.java
> 10주차 문제풀이 박진우

- week10/BOJ_16398/BOJ_16398_원민혁.java
- week10/BOJ_1916/BOJ_1916_원민혁.java
- week10/BOJ_4485/BOJ_4485_원민혁.java
> 10주차 문제풀이 원민혁

- week12/README.md
> 12주차 문제 출제

- week11/BOJ_11559/BOJ_11559_박진우.java
- week11/BOJ_15685/BOJ_15685_박진우.java
- week11/BOJ_20055/BOJ_20055_박진우.java
11주차 문제를 풀었습니다.
구현, 시뮬레이션 문제는 다음이 중요한 것 같아요.
- 요구사항 파악 및 논리적으로 정리
- 구현 내용 세분화 및 기능별 구분
- 단순 구현 이전에 패턴이 있는지 확인하기 (드래곤 커브를 너무 어렵게 풀고 있었어요)
> 11주차 문제풀이 박진우

- week11/BOJ_11559/BOJ_11559_원민혁.java
- week11/BOJ_20055/BOJ_20055_원민혁.java
> 11주차 알고리즘 원민혁

- week11/BOJ_15685/BOJ_15685_원민혁.java
- week12/BOJ_12865/BOJ_12865_원민혁.java
- week12/BOJ_14728/BOJ_14728_원민혁.java
- week12/BOJ_18427/BOJ_18427_원민혁.java
> 12주차 알고리즘 원민혁

- week12/BOJ_12865/BOJ_12865_이혜윤.java
- week12/BOJ_14728/BOJ_14728_이혜윤.java
dp 테이블을 직접 그려서 풀어보는 문제들은 처음이라 더 유익했습니다 :) 이번주 난이도 좋아용
> 이혜윤 12주차 문제풀이

- week12/BOJ_12865/BOJ_12865_박진우.java
- week12/BOJ_14728/BOJ_14728_박진우.java
- week12/BOJ_18427/BOJ_18427_박진우.java
> 12주차 문제풀이 박진우

- week13/BOJ_1240/BOJ_1240_이혜윤.java
- week13/BOJ_1967/BOJ_1967_이혜윤.java
end, cost 를 멤버변수로 가지는 Node 클래스를 만들어서 이를 List에 담는 풀이에 익숙해질 수 있어서 유익했습니당~
> 이혜윤 13주차 문제풀이

- week14/BOJ_1300/BOJ_1300_박진우.java
- week14/BOJ_1939/BOJ_1939_박진우.java
- week14/BOJ_2343/BOJ_2343_박진우.java
이분탐색 익숙한 유형만 풀다가, 이번주 문제는 새로운 유형이라 첫 접근이 조금 어려웠던 것 같습니다.
1939번은 다익스트라를 이용하여 풀이했습니다.
14주간 고생 많으셨습니다!
> 14주차 문제풀이 박진우

- week14/BOJ_1939/BOJ_1939_이혜윤.java
- week14/BOJ_2343/BOJ_2343_이혜윤.java
> 이혜윤 14주차 문제풀이
